### ISSUE TITLE
Permissions are ignored, ranks are "unavailable"

### ISSUE THREAD

**Issue by skerit** [BlockyBorzan/BlockyRanks#3]
I've noticed some issues:

- I have set the command permissions to `false`, but people are still able to do /ranks
- I feel like reloading the plugin using `/blockyranks reload` doesn't really work? I have to reboot the server after changes, or weird things happen
- When I try to give someone a rank like so `/blockyranks set username world novice`, I get the error "rank novice is unavailable in the specified worlds: [world, world_the_end, world_nether]`

**Comment by BlockyBorzan** [comment]
Hi, 

I have tried to reproduce your issues and have not been successful. 

In order to help you I would need to take a look at your configuration.

- Permissions are not handled by BlockyRanks itself, but by your Vault-hooked Permissions Handler plugin of choice. BlockyRanks does in fact register the commands properly and that is all it is supposed to do. Determining if a player can use that command is done by your permissions handler.

- "weird things" is not something I can test for. Could you be more specific, please? 

- This could be due to an error in your config or your server/world setup. 

I would love to help you so please feel free to reach out to me here or on spigotmc.org.

Also, I am sorry it took me 3 weeks to answer. I was on a business trip for 2 weeks and then had to test your issues...

Cheers,

Blocky
